spring:
  cloud:
    azure:
      storage:
        blob:
          account-name: ${ACCOUNT_NAME}
          account-key: ${ACCOUNT_KEY}
          endpoint: https://${ACCOUNT_NAME}.blob.core.windows.net/
          container-name: shopping-cart