springfoxdocumentation:
  swagger:
    v2:
      path: /api-docs
      
server:
  port: ${PETSTOREORDERSERVICE_SERVER_PORT:8080}

petstore:
  service:
    product:
      url: ${PETSTOREPRODUCTSERVICE_URL:http://localhost:8082}

spring:
  application:
    name: petstoreorderservice
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  cloud:
    azure:
      cosmos:
        endpoint: https://petstorecosmos.documents.azure.com:443/
        database: petstoreorderservice_db
        populate-query-metrics: true

management:
  endpoints:
    web:
      exposure:
        include: "*"       
  trace:
    http:
      enabled: true 
  endpoint:
    httptrace:
      enabled: true

container:
    name: alisacontainer
    connection-string: 'DefaultEndpointsProtocol=https;AccountName=alisapetstoresa;AccountKey=L7wbir5/dabVowKfHVJHHQNTErJXwLohcg/Gz6o1WKkXc1O52IJjV14cbg/ibge4RgPknUF1VPb++AStJYVnqw==;EndpointSuffix=core.windows.net'

email:
  uri: 'https://alisalogicapp.azurewebsites.net:443/api/orderEmail/triggers/When_a_HTTP_request_is_received/invoke?api-version=2022-05-01&sp=%2Ftriggers%2FWhen_a_HTTP_request_is_received%2Frun&sv=1.0&sig=hnp9P2cy6DRWDn_ZFvWADPiTX0ERrZIva05u0OjF7GY'

servicebus:
  connection-string: 'Endpoint=sb://alisapetstoresb.servicebus.windows.net/;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=F7/RXlNMNut9IAVUcP6uvzEqpH5SpsHrI+ASbBkqUr8='
  queue:
    name: queue